project_id = "lcualhkpezggwqqmlywc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lcualhkpezggwqqmlywc.supabase.co/auth/v1/callback", "http://localhost:5173"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.process-payment]
verify_jwt = true

[functions.create-card-token]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.get-mp-config]
verify_jwt = true