# supabase/config.toml
project_id = "atacado-canoa-front-95"

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

# --- CORREÇÃO FINAL AQUI ---
# A seção [functions."*"] foi removida e substituída 
# por declarações individuais para cada função.

[functions.process-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.get-mp-config]
verify_jwt = true

[functions.create-card-token]
verify_jwt = true

[functions.debug-payment]
verify_jwt = true