// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables directly for Vercel deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lcualhkpezggwqqmlywc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdWFsaGtwZXpnZ3dxcW1seXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjM3ODMsImV4cCI6MjA3MDY5OTc4M30.GTR9N2rpBiitzTxbKeDdiSfE6rE5Ac1Vjxd7VzOUYL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});